### ISSUE TITLE
Can't push new changes? 

### ISSUE THREAD

**Issue by ntshoe20** [Android-90-kabza/CTS-wizard#3]
The structure of the branch has changed. So what should you do? 
Step one you need to sync your branch with the  latest changes. No new changes can be push while there are new changes. 
>git pull -r
Step two: create a local branch, never work from the main branch.
>git branch feature/updatePages
>git checkout feature/updatePages
step three:Always create new branches from main or from development, depending which one has the latest changes.
>git checkout main
>git branch feature/updatePages
Step four: what ever changes you made, you can now make them in the new branch then save the changes locally and push the changes to github to be reviewed before merging into the development branch.
>git status (This checks which files have been modified)
>git add * (this adds all the files that were modified to the staging environment, ready to be committed)
>git commit -m "insert your commit message here"
>git push
If you get an error, just read how to resolve the error. 

In github create a pull request to merge your feature branch "feature/updatePages" to development branch.
Add me as a reviewer as second pair of eyes.

**Comment by ntshoe20** [comment]
@Android-90-kabza is this complete?

**Comment by Android-90-kabza** [comment]
> @Android-90-kabza is this complete?

if you are referring to the list above yes it's complete I followed the same steps more or less I just messed up by repeating commands cause laptop was very slow on the day, I want to complete the interface I'm busy with now I implemented those changes you suggested for naming the HTML file index.html and using less html files

**Comment by ntshoe20** [comment]
No comment
